// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_component_matrix
NumericMatrix calc_component_matrix(NumericVector p, NumericVector Ytrue, double phi, int n_pass);
RcppExport SEXP _methaneInventory_calc_component_matrix(SEXP pSEXP, SEXP YtrueSEXP, SEXP phiSEXP, SEXP n_passSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ytrue(YtrueSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< int >::type n_pass(n_passSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_component_matrix(p, Ytrue, phi, n_pass));
    return rcpp_result_gen;
END_RCPP
}
// calc_strat_matrix
NumericMatrix calc_strat_matrix(CharacterVector facility_ids, NumericVector psu_means, double nh, double Nh, int dimension);
RcppExport SEXP _methaneInventory_calc_strat_matrix(SEXP facility_idsSEXP, SEXP psu_meansSEXP, SEXP nhSEXP, SEXP NhSEXP, SEXP dimensionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type facility_ids(facility_idsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type psu_means(psu_meansSEXP);
    Rcpp::traits::input_parameter< double >::type nh(nhSEXP);
    Rcpp::traits::input_parameter< double >::type Nh(NhSEXP);
    Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_strat_matrix(facility_ids, psu_means, nh, Nh, dimension));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_methaneInventory_calc_component_matrix", (DL_FUNC) &_methaneInventory_calc_component_matrix, 4},
    {"_methaneInventory_calc_strat_matrix", (DL_FUNC) &_methaneInventory_calc_strat_matrix, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_methaneInventory(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
