# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_component_matrix <- function(p, Ytrue, phi, n_pass) {
    .Call('_methaneInventory_calc_component_matrix', PACKAGE = 'methaneInventory', p, Ytrue, phi, n_pass)
}

calc_strat_matrix <- function(facility_ids, psu_means, nh, Nh, dimension) {
    .Call('_methaneInventory_calc_strat_matrix', PACKAGE = 'methaneInventory', facility_ids, psu_means, nh, Nh, dimension)
}

